# Generated by Django 5.0.2 on 2024-02-15 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='gallaries'), blank=True, null=True, size=None),
        ),
    ]
