# Generated by Django 5.0.2 on 2024-02-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0002_gallary_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallary',
            name='images',
        ),
        migrations.CreateModel(
            name='GallaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallaries/images')),
                ('gallary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallary.gallary')),
            ],
        ),
    ]
