# Generated by Django 5.0.2 on 2024-02-15 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0003_remove_gallary_images_gallaryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallaryimage',
            name='gallary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallary.gallary'),
        ),
    ]
