# Generated by Django 5.0.2 on 2024-02-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0005_alter_gallaryimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallaryimage',
            old_name='image',
            new_name='pic',
        ),
    ]
