# Generated by Django 5.0.2 on 2024-02-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0006_rename_image_gallaryimage_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='gallary/downloads')),
            ],
        ),
    ]
