# Generated by Django 5.0.2 on 2024-02-15 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0007_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
