# Generated by Django 5.0.2 on 2024-02-16 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0008_downloads_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='main_galleries/thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='MainGallaryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='main_galleries/pictures')),
                ('main_gallary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallary.maingallary')),
            ],
        ),
    ]
