# Generated by Django 5.0.2 on 2024-02-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBAFeeStructureYear1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_Fee', models.BigIntegerField(max_length=200)),
                ('Annual_Fee', models.BigIntegerField(blank=True, null=True)),
                ('First_Aid', models.BigIntegerField(blank=True, null=True)),
                ('Student_Welfare_fund', models.BigIntegerField(blank=True, null=True)),
                ('Admission_Form_fee', models.BigIntegerField(blank=True, null=True)),
                ('Id_card', models.BigIntegerField(blank=True, max_length=50, null=True)),
                ('Exam_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Tie_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Total_Yearly_Fee', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BBAFeeStructureYear2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_Fee', models.BigIntegerField(max_length=200)),
                ('Annual_Fee', models.BigIntegerField(blank=True, null=True)),
                ('First_Aid', models.BigIntegerField(blank=True, null=True)),
                ('Student_Welfare_fund', models.BigIntegerField(blank=True, null=True)),
                ('Admission_Form_fee', models.BigIntegerField(blank=True, null=True)),
                ('Id_card', models.BigIntegerField(blank=True, max_length=50, null=True)),
                ('Exam_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Tie_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Total_Yearly_Fee', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BBAFeeStructureYear3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_Fee', models.BigIntegerField(max_length=200)),
                ('Annual_Fee', models.BigIntegerField(blank=True, null=True)),
                ('First_Aid', models.BigIntegerField(blank=True, null=True)),
                ('Student_Welfare_fund', models.BigIntegerField(blank=True, null=True)),
                ('Admission_Form_fee', models.BigIntegerField(blank=True, null=True)),
                ('Id_card', models.BigIntegerField(blank=True, max_length=50, null=True)),
                ('Exam_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Tie_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Total_Yearly_Fee', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BBAFeeStructureYear4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_Fee', models.BigIntegerField(max_length=200)),
                ('Annual_Fee', models.BigIntegerField(blank=True, null=True)),
                ('First_Aid', models.BigIntegerField(blank=True, null=True)),
                ('Student_Welfare_fund', models.BigIntegerField(blank=True, null=True)),
                ('Admission_Form_fee', models.BigIntegerField(blank=True, null=True)),
                ('Id_card', models.BigIntegerField(blank=True, max_length=50, null=True)),
                ('Exam_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Tie_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Total_Yearly_Fee', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bbafeestructure',
            name='admission_fees',
        ),
        migrations.DeleteModel(
            name='AdmissionFee',
        ),
        migrations.DeleteModel(
            name='BBAFeeStructure',
        ),
    ]
