# Generated by Django 5.0.2 on 2024-02-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_remove_bbafeestructureyear1_total_yearly_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
            ],
        ),
    ]
