# Generated by Django 5.0.2 on 2024-02-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_bbafeestructureyear1_pdf_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePdf',
        ),
    ]
