# Generated by Django 5.0.2 on 2024-02-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_alter_bbafeestructureyear3_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbafeestructureyear1',
            name='pdf_file',
            field=models.ImageField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
