# Generated by Django 5.0.2 on 2024-02-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='totalyear',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
