# Generated by Django 5.0.2 on 2024-02-14 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_courses_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbafeestructureyear1',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.courses'),
        ),
    ]
