# Generated by Django 5.0.2 on 2024-02-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_bbafeestructureyear1_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbafeestructureyear2',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.courses'),
        ),
        migrations.AddField(
            model_name='bbafeestructureyear3',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.courses'),
        ),
        migrations.AddField(
            model_name='bbafeestructureyear4',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.courses'),
        ),
    ]
