# Generated by Django 5.0.2 on 2024-02-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_bbafeestructureyear2_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBSFeeStructureYear1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_Fee', models.BigIntegerField(max_length=200)),
                ('Annual_Fee', models.BigIntegerField(blank=True, null=True)),
                ('First_Aid', models.BigIntegerField(blank=True, null=True)),
                ('Student_Welfare_fund', models.BigIntegerField(blank=True, null=True)),
                ('Admission_Form_fee', models.BigIntegerField(blank=True, null=True)),
                ('Id_card', models.BigIntegerField(blank=True, max_length=50, null=True)),
                ('Exam_Fee', models.BigIntegerField(blank=True, null=True)),
                ('Tie_Fee', models.BigIntegerField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.courses')),
            ],
        ),
    ]
