# Generated by Django 5.0.2 on 2024-02-13 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notices_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='topics',
            field=models.TextField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
