# Generated by Django 5.0.2 on 2024-02-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_remove_news_title_news_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topics',
            field=models.CharField(max_length=100),
        ),
    ]
