# Generated by Django 5.0.2 on 2024-02-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorymembers',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='advisors/'),
        ),
        migrations.AddField(
            model_name='boardmembers',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='board/'),
        ),
        migrations.AddField(
            model_name='patronmembers',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='patrons/'),
        ),
    ]
